version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./data:/data
  tesseract:
    build:
      context: .
      dockerfile: Dockerfile.tesseract
    volumes:
      - ./data:/data
  redis:
    image: "redis:alpine"


