FROM python:3.8-slim

RUN apt-get update && apt-get install -y tesseract-ocr

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

CMD ["python", "server.py"]
